# Generated by Django 3.2.4 on 2023-05-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField()),
                ('smtp_id', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=50)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sg_event_id', models.CharField(max_length=100)),
                ('sg_message_id', models.CharField(max_length=100)),
                ('response', models.CharField(blank=True, max_length=100, null=True)),
                ('attempt', models.IntegerField(blank=True, null=True)),
                ('sg_machine_open', models.BooleanField(blank=True, null=True)),
                ('useragent', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('bounce_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
