# Generated by Django 3.2.4 on 2023-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campanha', models.CharField(max_length=60)),
                ('id_campanha', models.IntegerField()),
                ('message_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('data_hora_envio', models.DateTimeField()),
                ('data_hora_update', models.DateTimeField(auto_now=True)),
                ('contato_id', models.IntegerField()),
            ],
        ),
    ]
